// src/utils/countryCurrencyOptions.js
export const countryCurrencyOptions = [
  { country: 'Cameroon', countryCode: 'CM', currency: 'XAF', payWithMtn: 'CM_MTNMOMO', payWithOrange: 'CM_ORANGE' },
  { country: 'Nigeria', countryCode: 'NG', currency: 'NGN', payWithMtn: 'NG_MTNMOMO', payWithOrange: 'NG_ORANGE' },
  { country: 'Ghana', countryCode: 'GH', currency: 'GHS', payWithMtn: 'GH_MTNMOMO', payWithOrange: 'GH_ORANGE' },
  { country: 'Ivory Coast', countryCode: 'CI', currency: 'XOF', payWithMtn: 'CI_MTNMOMO', payWithOrange: 'CI_ORANGE' },
  { country: 'Senegal', countryCode: 'SN', currency: 'XOF', payWithMtn: 'SN_MTNMOMO', payWithOrange: 'SN_ORANGE' },
  { country: 'Mali', countryCode: 'ML', currency: 'XOF', payWithMtn: 'ML_MTNMOMO', payWithOrange: 'ML_ORANGE' },
  { country: 'Burkina Faso', countryCode: 'BF', currency: 'XOF', payWithMtn: 'BF_MTNMOMO', payWithOrange: 'BF_ORANGE' },
  { country: 'Togo', countryCode: 'TG', currency: 'XOF', payWithMtn: 'TG_MTNMOMO', payWithOrange: 'TG_ORANGE' },
  { country: 'Benin', countryCode: 'BJ', currency: 'XOF', payWithMtn: 'BJ_MTNMOMO', payWithOrange: 'BJ_ORANGE' },
  { country: 'Gabon', countryCode: 'GA', currency: 'XAF', payWithMtn: 'GA_MTNMOMO', payWithOrange: 'GA_ORANGE' },
  { country: 'Central African Republic', countryCode: 'CF', currency: 'XAF', payWithMtn: 'CF_MTNMOMO', payWithOrange: 'CF_ORANGE' },
  { country: 'Republic of Congo', countryCode: 'CG', currency: 'XAF', payWithMtn: 'CG_MTNMOMO', payWithOrange: 'CG_ORANGE' },
  { country: 'Democratic Republic of Congo', countryCode: 'CD', currency: 'CDF', payWithMtn: 'CD_MTNMOMO', payWithOrange: 'CD_ORANGE' },
  { country: 'Equatorial Guinea', countryCode: 'GQ', currency: 'XAF', payWithMtn: 'GQ_MTNMOMO', payWithOrange: 'GQ_ORANGE' },
    { country: 'Cameroon', countryCode: 'CM', currency: 'XAF', payWithMtn: 'CM_MTNMOMO', payWithOrange: 'CM_ORANGE' },
    { country: 'South Africa', countryCode: 'ZA', currency: 'ZAR', payWithMtn: 'ZA_MTNMOMO', payWithOrange: 'ZA_ORANGE' },
    { country: 'Kenya', countryCode: 'KE', currency: 'KES', payWithMtn: 'KE_MTNMOMO', payWithOrange: 'KE_ORANGE' },
    { country: 'Uganda', countryCode: 'UG', currency: 'UGX', payWithMtn: 'UG_MTNMOMO', payWithOrange: 'UG_ORANGE' },
    { country: 'Tanzania', countryCode: 'TZ', currency: 'TZS', payWithMtn: 'TZ_MTNMOMO', payWithOrange: 'TZ_ORANGE' },
    { country: 'Zambia', countryCode: 'ZM', currency: 'ZMW', payWithMtn: 'ZM_MTNMOMO', payWithOrange: 'ZM_ORANGE' },
    { country: 'Rwanda', countryCode: 'RW', currency: 'RWF', payWithMtn: 'RW_MTNMOMO', payWithOrange: 'RW_ORANGE' },
    { country: 'Botswana', countryCode: 'BW', currency: 'BWP', payWithMtn: 'BW_MTNMOMO', payWithOrange: 'BW_ORANGE' },
    { country: 'Lesotho', countryCode: 'LS', currency: 'LSL', payWithMtn: 'LS_MTNMOMO', payWithOrange: 'LS_ORANGE' },
    { country: 'Eswatini', countryCode: 'SZ', currency: 'SZL', payWithMtn: 'SZ_MTNMOMO', payWithOrange: 'SZ_ORANGE' },
    { country: 'Namibia', countryCode: 'NA', currency: 'NAD', payWithMtn: 'NA_MTNMOMO', payWithOrange: 'NA_ORANGE' },
    { country: 'Sierra Leone', countryCode: 'SL', currency: 'SLL', payWithMtn: 'SL_MTNMOMO', payWithOrange: 'SL_ORANGE' },
    { country: 'Liberia', countryCode: 'LR', currency: 'LRD', payWithMtn: 'LR_MTNMOMO', payWithOrange: 'LR_ORANGE' },
    { country: 'Mauritius', countryCode: 'MU', currency: 'MUR', payWithMtn: 'MU_MTNMOMO', payWithOrange: 'MU_ORANGE' },
    { country: 'Malawi', countryCode: 'MW', currency: 'MWK', payWithMtn: 'MW_MTNMOMO', payWithOrange: 'MW_ORANGE' },
    { country: 'Zimbabwe', countryCode: 'ZW', currency: 'ZWL', payWithMtn: 'ZW_MTNMOMO', payWithOrange: 'ZW_ORANGE' },
    { country: 'Tanzania', countryCode: 'TZ', currency: 'TZS', payWithMtn: 'TZ_MTNMOMO', payWithOrange: 'TZ_ORANGE' },
    { country: 'Burundi', countryCode: 'BI', currency: 'BIF', payWithMtn: 'BI_MTNMOMO', payWithOrange: 'BI_ORANGE' },
    { country: 'Kenya', countryCode: 'KE', currency: 'KES', payWithMtn: 'KE_MTNMOMO', payWithOrange: 'KE_ORANGE' },
  // Add more as you support
];